### ISSUE TITLE
PVP typo?

### ISSUE THREAD

**Issue by BuckarooBanzay** [Emojigit/anti_lava_area#1]
i guess you copied that from the `pvp_areas` mod :smile: 
Its still in the description:
https://github.com/Emojigit/anti_lava_area/blob/4da158f65509c03d35a4d0a4807c04c78bd6b25b/init.lua#L88

**Comment by Emojigit** [comment]
XD, I will correct it now.

**Comment by Emojigit** [comment]
Okay, fixed
